#! /usr/bin/python
# -*- coding: utf-8 -*-

import sys
import GpLog
from GpReCutImg import ReCutImg

def main():
	rc = ReCutImg()	
	fileName=sys.argv[1]
	if fileName == 'mongo':
		rc.rcFormMongo()
	else:
		GpLog.debug("file : "+fileName)	
		file = open(fileName)
		for line in file.xreadlines():
			line = line.rstrip()
			GpLog.debug(line)
			GpLog.debug("==============")
			mydata = line.split(" ")
			if len(mydata)==2:
		        	try:
					rc.rcImage(mydata[0],mydata[1])
		        	except Exception,ex:
					GpLog.error("rmfile storageId|"+mydata[0]+"|corbisId|"+mydata[1]) 
					print traceback.format_exc()
			elif len(mydata) == 3:
				try:
					rc.rcImage(mydata[0],mydata[1],mydata[2])
		        	except Exception,ex:
					GpLog.error("rmfile storageId|"+mydata[0]+"|corbisId|"+mydata[1]) 
					print traceback.format_exc()

		file.close()

if __name__ == '__main__':
	main()
